import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../core/export_service.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('vi'), Locale('en'), Locale('ja')];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String get languageCode => _supportedLanguage(locale.languageCode);

  String t(String key) =>
      _values[languageCode]?[key] ?? _values['vi']![key] ?? key;

  String error(String? key) => key == null ? t('unknownError') : t(key);

  ExportReportLabels get exportReportLabels => ExportReportLabels(
    title: t('monthlyReportTextTitle'),
    reportMonth: t('reportMonth'),
    reportPeriod: reportPeriod,
    totalBalance: t('totalBalance'),
    monthIncome: t('thisMonthIncome'),
    monthExpense: t('thisMonthExpense'),
    netCashflow: t('netCashflow'),
    budgetAlerts: t('budgetAlerts'),
    metric: t('metric'),
    value: t('value'),
    recentTransactions: t('recentTransactions'),
    noTransactions: t('noTransactions'),
    date: t('date'),
    type: t('type'),
    wallet: t('wallets'),
    category: t('category'),
    amount: t('amount'),
    note: t('note'),
    formatDate: shortDate,
    formatTransactionType: (type) => t(type.name),
  );

  String monthYear(DateTime month) => switch (languageCode) {
    'en' => '${_englishMonths[month.month - 1]} ${month.year}',
    'ja' => '${month.year}年${month.month}月',
    _ => 'Tháng ${month.month}/${month.year}',
  };

  String shortDate(DateTime date) => switch (languageCode) {
    'en' => '${date.month}/${date.day}/${date.year}',
    'ja' => '${date.year}/${date.month}/${date.day}',
    _ => '${date.day}/${date.month}/${date.year}',
  };

  String netCashflow(String amount) => switch (languageCode) {
    'en' => 'Net cashflow: $amount',
    'ja' => '純キャッシュフロー: $amount',
    _ => 'Dòng tiền ròng: $amount',
  };

  String budgetAlertCount(int count) => switch (languageCode) {
    'en' => '$count budgets near/over limit',
    'ja' => '$count 件の予算が上限に接近/超過',
    _ => '$count ngân sách gần/vượt hạn mức',
  };

  String incomeExpenseChartSemantics(
    String income,
    String expense,
  ) => switch (languageCode) {
    'en' =>
      'Income and expense chart this month. Income $income, expense $expense.',
    'ja' => '今月の収入と支出のグラフ。収入 $income、支出 $expense。',
    _ => 'Biểu đồ thu chi tháng này. Thu $income, chi $expense.',
  };

  String remainingGoal(String amount, DateTime deadline) =>
      switch (languageCode) {
        'en' => '$amount left by ${shortDate(deadline)}',
        'ja' => '${shortDate(deadline)}まで残り $amount',
        _ => 'Còn $amount đến ${shortDate(deadline)}',
      };

  String monthlySavingSuggestion(String amount) => switch (languageCode) {
    'en' => 'Suggested saving $amount/month',
    'ja' => '毎月の推奨貯蓄額 $amount',
    _ => 'Gợi ý tiết kiệm $amount/tháng',
  };

  String dueDate(DateTime date) => switch (languageCode) {
    'en' => 'Due ${date.month}/${date.day}',
    'ja' => '期限 ${date.month}/${date.day}',
    _ => 'Đến hạn ${date.day}/${date.month}',
  };

  String budgetProgressSemantics(String category, String spent, String limit) =>
      switch (languageCode) {
        'en' => 'Budget $category: used $spent of $limit.',
        'ja' => '予算 $category: $limit 中 $spent 使用済み。',
        _ => 'Ngân sách $category: đã dùng $spent trên $limit.',
      };

  String budgetRemaining(String amount) => switch (languageCode) {
    'en' => 'Remaining: $amount',
    'ja' => '残り: $amount',
    _ => 'Còn lại: $amount',
  };

  String categoryExpenseChartSemantics(String summary) =>
      switch (languageCode) {
        'en' => 'Expense by category chart: $summary.',
        'ja' => 'カテゴリ別支出グラフ: $summary。',
        _ => 'Biểu đồ chi tiêu theo danh mục: $summary.',
      };

  String deadline(DateTime date) => switch (languageCode) {
    'en' => 'Deadline ${shortDate(date)}',
    'ja' => '期限 ${shortDate(date)}',
    _ => 'Hạn chót ${shortDate(date)}',
  };

  String reportPeriod(DateTime month) => switch (languageCode) {
    'en' => 'Report period: ${monthYear(month)}',
    'ja' => 'レポート期間: ${monthYear(month)}',
    _ => 'Kỳ báo cáo: ${month.month}/${month.year}',
  };

  static String _supportedLanguage(String code) => switch (code) {
    'en' => 'en',
    'ja' => 'ja',
    _ => 'vi',
  };
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['vi', 'en', 'ja'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const _englishMonths = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

const _values = {
  'vi': {
    'addBudget': 'Thêm ngân sách',
    'addGoal': 'Thêm mục tiêu',
    'addTransaction': 'Thêm giao dịch',
    'all': 'Tất cả',
    'allCategories': 'Tất cả danh mục',
    'allMonths': 'Tất cả tháng',
    'allWallets': 'Tất cả ví',
    'amount': 'Số tiền',
    'accountSync': 'Tài khoản & đồng bộ',
    'accountSyncSignedOut':
        'Đăng nhập để bật đồng bộ đám mây, premium và ngân sách chung.',
    'amountInvalid': 'Số tiền không hợp lệ',
    'amountPositive': 'Số tiền phải lớn hơn 0',
    'backupCreated': 'Đã tạo file backup JSON.',
    'backupExportFailed': 'Không xuất được backup trên thiết bị này.',
    'backupIntro':
        'Xuất file JSON offline hoặc khôi phục dữ liệu từ file backup CashFlow Manager.',
    'backupRestore': 'Sao lưu / khôi phục',
    'backupRestoreData': 'Sao lưu / khôi phục dữ liệu',
    'backupRestoreSubtitle': 'Xuất và khôi phục file JSON offline',
    'backupSensitiveWarning':
        'File backup chứa dữ liệu tài chính nhạy cảm. Chỉ chia sẻ hoặc lưu ở nơi bạn tin cậy.',
    'backupCategoryRequired': 'Backup phải có ít nhất một danh mục',
    'backupDuplicateId': 'Backup có mã dữ liệu bị trùng',
    'backupInvalidDate': 'Backup có ngày không hợp lệ',
    'backupInvalidExportTime': 'Thời gian export không hợp lệ',
    'backupInvalidFile': 'File backup không hợp lệ',
    'backupInvalidRow': 'Dòng dữ liệu backup không hợp lệ',
    'backupInvalidType': 'Backup có loại dữ liệu không hợp lệ',
    'backupMissingCategoryReference':
        'Backup tham chiếu danh mục không tồn tại',
    'backupMissingData': 'Backup thiếu dữ liệu bắt buộc',
    'backupMissingField': 'Backup thiếu trường bắt buộc',
    'backupMissingTargetWalletReference':
        'Backup tham chiếu ví nhận không tồn tại',
    'backupMissingWalletReference': 'Backup tham chiếu ví không tồn tại',
    'backupNonNegativeNumberRequired': 'Backup có số tiền âm không hợp lệ',
    'backupPositiveNumberRequired': 'Backup có số tiền phải lớn hơn 0',
    'backupUnsupportedVersion': 'Phiên bản backup không được hỗ trợ',
    'backupWalletRequired': 'Backup phải có ít nhất một ví',
    'biometricFailed': 'Không thể xác thực sinh trắc học',
    'biometricUnlock': 'Mở bằng sinh trắc học',
    'biometricUnlockSetting': 'Mở khóa sinh trắc học',
    'biometricUnlockEnabled': 'Đang bật cho lần mở khóa sau',
    'biometricUnlockDisabled': 'Tắt cho đến khi bạn xác thực và bật lại',
    'biometricEnableReason': 'Xác thực để bật mở khóa sinh trắc học',
    'biometricEnableFailed':
        'Không thể bật sinh trắc học. PIN vẫn dùng bình thường.',
    'biometricRequiresPin': 'Tạo PIN trước khi bật sinh trắc học',
    'biometricUnavailable': 'Thiết bị chưa hỗ trợ hoặc chưa cài sinh trắc học',
    'budgetAlerts': 'Cảnh báo ngân sách',
    'budgetThisMonth': 'Ngân sách tháng này',
    'budgets': 'Ngân sách',
    'cancel': 'Hủy',
    'cashflowForecast': 'Dự báo dòng tiền',
    'cashflowThisMonth': 'Thu chi tháng này',
    'category': 'Danh mục',
    'categoryExpense': 'Danh mục chi',
    'categoryExpenseChartEmpty': 'Chưa có chi tiêu trong tháng này',
    'close': 'Đóng',
    'currency': 'Tiền tệ mặc định',
    'csvTransactions': 'Giao dịch CSV',
    'dashboard': 'Tổng quan',
    'defaultCurrency': 'VND',
    'delete': 'Xóa',
    'deleteBudget': 'Xóa ngân sách',
    'deleteBudgetQuestion': 'Xóa ngân sách?',
    'deleteBudgetWarning': 'Ngân sách này sẽ bị xóa khỏi tháng đã chọn.',
    'deleteGoal': 'Xóa mục tiêu',
    'deleteGoalQuestion': 'Xóa mục tiêu?',
    'deleteGoalWarning': 'Mục tiêu tiết kiệm này sẽ bị xóa.',
    'deleteTransaction': 'Xóa giao dịch',
    'deleteTransactionQuestion': 'Xóa giao dịch?',
    'date': 'Ngày',
    'expense': 'Chi',
    'expenseCategoryChart': 'Chi tiêu theo danh mục',
    'expenseWalletCategory': 'Ví / tài khoản',
    'email': 'Email',
    'exportBackupJson': 'Xuất backup JSON',
    'exportCsvPdf': 'Xuất CSV/PDF',
    'exportReportContent': 'Nội dung xuất báo cáo',
    'exportSensitiveWarning':
        'Báo cáo xuất ra có thể chứa dữ liệu tài chính nhạy cảm. Chỉ chia sẻ với người hoặc ứng dụng bạn tin cậy.',
    'forecastCurrentMonthEnd': 'Cuối tháng này',
    'forecastNextMonthEnd': 'Dự kiến cuối tháng sau',
    'futureCashflow': 'Dòng tiền tương lai',
    'goalName': 'Tên mục tiêu',
    'goalSavedAmount': 'Đã tiết kiệm',
    'goalSavedExceedsTarget': 'Số tiền đã tiết kiệm vượt mục tiêu',
    'goalTargetAmount': 'Số tiền mục tiêu',
    'goals': 'Mục tiêu tiết kiệm',
    'income': 'Thu',
    'language': 'Ngôn ngữ',
    'languageEnglish': 'Tiếng Anh',
    'languageJapanese': 'Tiếng Nhật',
    'languageVietnamese': 'Tiếng Việt',
    'login': 'Đăng nhập',
    'logout': 'Đăng xuất',
    'loadDataFailed': 'Không tải được dữ liệu',
    'monthlyLimit': 'Hạn mức tháng',
    'monthAfter': 'Tháng sau',
    'monthBefore': 'Tháng trước',
    'metric': 'Chỉ số',
    'monthlyReportTextTitle': 'CashFlow Manager - Báo cáo tháng',
    'monthFilter': 'Lọc theo tháng',
    'netCashflow': 'Dòng tiền ròng',
    'nextBills': 'Nhắc hóa đơn sắp tới',
    'monthlyTrend': 'Xu hướng thu chi 4 tháng',
    'includedInForecast': 'Đã tính trong dự báo',
    'noTrendData': 'Chưa có dữ liệu xu hướng',
    'noBudgets': 'Chưa có ngân sách',
    'noRecurringExpenses': 'Chưa có giao dịch chi lặp lại',
    'noSavingGoals': 'Chưa có mục tiêu tiết kiệm',
    'noTransactions': 'Chưa có giao dịch',
    'note': 'Ghi chú',
    'recentTransactions': 'Giao dịch gần đây',
    'confirm': 'Xác nhận',
    'reauthSubtitle':
        'Nhập lại PIN trước khi thay đổi hoặc thay thế dữ liệu tài chính.',
    'reauthTitle': 'Xác thực lại',
    'reportMonth': 'Báo cáo tháng',
    'reports': 'Báo cáo',
    'recurringTransaction': 'Giao dịch lặp lại',
    'pinConfirm': 'Nhập lại PIN',
    'pinCooldownActive':
        'Bạn nhập sai PIN quá nhiều lần. Vui lòng thử lại sau 5 phút.',
    'pinCreate': 'Tạo PIN',
    'pinCreateTitle': 'Bảo vệ dữ liệu tài chính',
    'pinInvalid': 'PIN không đúng',
    'pinMismatch': 'PIN nhập lại không khớp',
    'pinLengthInvalid': 'PIN phải có 4-6 chữ số',
    'pinNew': 'PIN mới',
    'pinSaveFailed': 'Không thể lưu PIN trên thiết bị này',
    'pinUnlock': 'Mở khóa',
    'pinUnlockFailed': 'Không thể kiểm tra PIN trên thiết bị này',
    'pinUnlockSubtitle': 'Nhập PIN để tiếp tục quản lý chi tiêu.',
    'pinUnlockTitle': 'Mở khóa CashFlow Manager',
    'privacyLock': 'Khóa riêng tư / PIN',
    'privacyLockEnabled': 'Đang bật',
    'privacyLockDisabled': 'Chưa tạo',
    'privacyLockSubtitle':
        'PIN luôn dự phòng; sinh trắc học chỉ bật khi bạn chọn.',
    'restoreCancelled': 'Đã hủy khôi phục dữ liệu.',
    'restoreConfirm': 'Khôi phục',
    'restoreConfirmTitle': 'Xác nhận khôi phục dữ liệu',
    'restoreExportMissing': 'Không có thời gian export',
    'restoreFailed': 'Không khôi phục được backup trên thiết bị này.',
    'restoreFileReadFailed': 'Không đọc được file backup',
    'restoreFileTooLarge': 'File backup vượt quá 5 MB',
    'restoreFormatFailed': 'Không khôi phục được: {message}',
    'restoreReplaceWarning':
        'Khôi phục sẽ thay thế toàn bộ dữ liệu hiện tại trên thiết bị này.',
    'restoreSuccess': 'Đã khôi phục dữ liệu thành công.',
    'restoreFromJson': 'Khôi phục từ file JSON',
    'saveBudget': 'Lưu ngân sách',
    'saveGoal': 'Lưu mục tiêu',
    'saveTransaction': 'Lưu giao dịch',
    'resetData': 'Đặt lại dữ liệu',
    'resetDataConfirmTitle': 'Xác nhận đặt lại dữ liệu',
    'resetDataSuccess': 'Đã reset dữ liệu về trạng thái ban đầu.',
    'resetDataSubtitle': 'Yêu cầu xác nhận trước khi xóa',
    'resetDataWarning':
        'Thao tác này sẽ xóa dữ liệu tài chính hiện tại và tạo lại dữ liệu mẫu ban đầu.',
    'searchTransactions': 'Tìm theo ghi chú hoặc danh mục',
    'settings': 'Cài đặt',
    'sharePdf': 'Chia sẻ PDF',
    'systemTheme': 'Hệ thống',
    'theme': 'Giao diện',
    'thisMonthIncome': 'Thu tháng này',
    'type': 'Loại',
    'thisMonthExpense': 'Chi tháng này',
    'topExpenseCategories': 'Danh mục chi tiêu nhiều nhất',
    'topExpenseCategoriesEmpty': 'Chưa đủ dữ liệu xếp hạng',
    'totalBalance': 'Tổng số dư hiện tại',
    'transactions': 'Giao dịch',
    'transactionSearchEmpty': 'Không có giao dịch phù hợp',
    'transfer': 'Chuyển ví',
    'transactionSaveFailed': 'Không thể lưu giao dịch trên thiết bị này',
    'transferBetweenWallets': 'Chuyển tiền giữa ví',
    'transferNow': 'Thực hiện chuyển ví',
    'transferring': 'Đang chuyển...',
    'value': 'Giá trị',
    'updateBudget': 'Cập nhật ngân sách',
    'updateGoal': 'Cập nhật mục tiêu',
    'unknownError': 'Không thể hoàn tất thao tác trên thiết bị này',
    'updateTransaction': 'Cập nhật giao dịch',
    'pinCreateSubtitle':
        'Tạo PIN 4-6 số để khóa dữ liệu thu chi trên thiết bị này.',
    'password': 'Mật khẩu',
    'premiumActive': 'Premium đang hoạt động',
    'premiumLocked': 'Tài khoản miễn phí, các tính năng premium đang khóa',
    'register': 'Đăng ký',
    'syncAuthFailed':
        'Không thể đăng nhập. Kiểm tra email, mật khẩu hoặc mạng.',
    'syncNow': 'Đồng bộ',
    'syncServerUnavailable': 'Máy chủ đồng bộ không khả dụng',
    'syncSessionUnavailable': 'Không đọc được phiên đồng bộ trên thiết bị này',
    'syncStatusSynced': 'Đã đồng bộ trạng thái tài khoản',
    'themeDark': 'Tối',
    'themeLight': 'Sáng',
    'walletCash': 'Tiền mặt',
    'walletBank': 'Ngân hàng',
    'walletCreditCard': 'Thẻ tín dụng',
    'walletDestination': 'Ví nhận',
    'walletEWallet': 'Ví điện tử',
    'walletSameTransferError': 'Ví nguồn và ví nhận phải khác nhau',
    'walletSource': 'Ví nguồn',
    'wallets': 'Ví',
  },
  'en': {
    'addBudget': 'Add budget',
    'addGoal': 'Add goal',
    'addTransaction': 'Add transaction',
    'all': 'All',
    'allCategories': 'All categories',
    'allMonths': 'All months',
    'allWallets': 'All wallets',
    'amount': 'Amount',
    'accountSync': 'Account & sync',
    'accountSyncSignedOut':
        'Sign in to enable cloud sync, premium, and shared budgets.',
    'amountInvalid': 'Invalid amount',
    'amountPositive': 'Amount must be greater than 0',
    'backupCreated': 'Backup JSON file created.',
    'backupExportFailed': 'Could not export backup on this device.',
    'backupIntro':
        'Export an offline JSON file or restore data from a CashFlow Manager backup.',
    'backupRestore': 'Backup / restore',
    'backupRestoreData': 'Backup / restore data',
    'backupRestoreSubtitle': 'Export and restore offline JSON files',
    'backupSensitiveWarning':
        'Backup files contain sensitive financial data. Share or store them only in places you trust.',
    'backupCategoryRequired': 'Backup must include at least one category',
    'backupDuplicateId': 'Backup contains duplicate data IDs',
    'backupInvalidDate': 'Backup contains an invalid date',
    'backupInvalidExportTime': 'Invalid export time',
    'backupInvalidFile': 'Invalid backup file',
    'backupInvalidRow': 'Invalid backup data row',
    'backupInvalidType': 'Backup contains an invalid data type',
    'backupMissingCategoryReference': 'Backup references a missing category',
    'backupMissingData': 'Backup is missing required data',
    'backupMissingField': 'Backup is missing a required field',
    'backupMissingTargetWalletReference':
        'Backup references a missing destination wallet',
    'backupMissingWalletReference': 'Backup references a missing wallet',
    'backupNonNegativeNumberRequired':
        'Backup contains an invalid negative amount',
    'backupPositiveNumberRequired':
        'Backup contains an amount that must be greater than 0',
    'backupUnsupportedVersion': 'Unsupported backup version',
    'backupWalletRequired': 'Backup must include at least one wallet',
    'biometricFailed': 'Could not authenticate with biometrics',
    'biometricUnlock': 'Unlock with biometrics',
    'biometricUnlockSetting': 'Biometric unlock',
    'biometricUnlockEnabled': 'Enabled for the next unlock',
    'biometricUnlockDisabled': 'Off until you authenticate and enable it',
    'biometricEnableReason': 'Authenticate to enable biometric unlock',
    'biometricEnableFailed': 'Could not enable biometrics. PIN still works.',
    'biometricRequiresPin': 'Create a PIN before enabling biometrics',
    'biometricUnavailable': 'Biometrics are not available on this device',
    'budgetAlerts': 'Budget alerts',
    'budgetThisMonth': 'This month budget',
    'budgets': 'Budgets',
    'cancel': 'Cancel',
    'cashflowForecast': 'Cashflow forecast',
    'cashflowThisMonth': 'Monthly income vs expense',
    'category': 'Category',
    'categoryExpense': 'Expense category',
    'categoryExpenseChartEmpty': 'No expenses this month',
    'close': 'Close',
    'currency': 'Default currency',
    'csvTransactions': 'CSV transactions',
    'dashboard': 'Overview',
    'defaultCurrency': 'VND',
    'delete': 'Delete',
    'deleteBudget': 'Delete budget',
    'deleteBudgetQuestion': 'Delete budget?',
    'deleteBudgetWarning':
        'This budget will be removed from the selected month.',
    'deleteGoal': 'Delete goal',
    'deleteGoalQuestion': 'Delete goal?',
    'deleteGoalWarning': 'This saving goal will be deleted.',
    'deleteTransaction': 'Delete transaction',
    'deleteTransactionQuestion': 'Delete transaction?',
    'date': 'Date',
    'expense': 'Expense',
    'expenseCategoryChart': 'Expense by category',
    'expenseWalletCategory': 'Wallet / account',
    'email': 'Email',
    'exportBackupJson': 'Export backup JSON',
    'exportCsvPdf': 'Export CSV/PDF',
    'exportReportContent': 'Report export content',
    'exportSensitiveWarning':
        'Exported reports may contain sensitive financial data. Share only with people or apps you trust.',
    'forecastCurrentMonthEnd': 'Projected current month end',
    'forecastNextMonthEnd': 'Projected next month end',
    'futureCashflow': 'Future cashflow',
    'goalName': 'Goal name',
    'goalSavedAmount': 'Saved amount',
    'goalSavedExceedsTarget': 'Saved amount exceeds target amount',
    'goalTargetAmount': 'Target amount',
    'goals': 'Saving goals',
    'income': 'Income',
    'language': 'Language',
    'languageEnglish': 'English',
    'languageJapanese': 'Japanese',
    'languageVietnamese': 'Vietnamese',
    'login': 'Log in',
    'logout': 'Log out',
    'loadDataFailed': 'Could not load data',
    'monthlyLimit': 'Monthly limit',
    'monthAfter': 'Next month',
    'monthBefore': 'Previous month',
    'metric': 'Metric',
    'monthlyReportTextTitle': 'CashFlow Manager - Monthly report',
    'monthFilter': 'Filter by month',
    'netCashflow': 'Net cashflow',
    'nextBills': 'Upcoming bill reminders',
    'monthlyTrend': '4-month income and expense trend',
    'includedInForecast': 'Included in forecast',
    'noTrendData': 'No trend data yet',
    'noBudgets': 'No budgets yet',
    'noRecurringExpenses': 'No recurring expenses yet',
    'noSavingGoals': 'No saving goals yet',
    'noTransactions': 'No transactions yet',
    'note': 'Note',
    'recentTransactions': 'Recent transactions',
    'confirm': 'Confirm',
    'reauthSubtitle':
        'Enter your PIN again before changing or replacing financial data.',
    'reauthTitle': 'Re-authenticate',
    'reportMonth': 'Monthly report',
    'reports': 'Reports',
    'recurringTransaction': 'Recurring transaction',
    'pinConfirm': 'Confirm PIN',
    'pinCooldownActive':
        'Too many incorrect PIN attempts. Please try again in 5 minutes.',
    'pinCreate': 'Create PIN',
    'pinCreateTitle': 'Protect financial data',
    'pinInvalid': 'Incorrect PIN',
    'pinMismatch': 'PIN confirmation does not match',
    'pinLengthInvalid': 'PIN must be 4-6 digits',
    'pinNew': 'New PIN',
    'pinSaveFailed': 'Could not save PIN on this device',
    'pinUnlock': 'Unlock',
    'pinUnlockFailed': 'Could not verify PIN on this device',
    'pinUnlockSubtitle': 'Enter PIN to continue managing spending.',
    'pinUnlockTitle': 'Unlock CashFlow Manager',
    'privacyLock': 'Privacy lock / PIN',
    'privacyLockEnabled': 'Enabled',
    'privacyLockDisabled': 'Not set',
    'privacyLockSubtitle':
        'PIN always remains available; biometrics are opt-in.',
    'restoreCancelled': 'Data restore cancelled.',
    'restoreConfirm': 'Restore',
    'restoreConfirmTitle': 'Confirm data restore',
    'restoreExportMissing': 'No export time',
    'restoreFailed': 'Could not restore backup on this device.',
    'restoreFileReadFailed': 'Could not read backup file',
    'restoreFileTooLarge': 'Backup file is larger than 5 MB',
    'restoreFormatFailed': 'Could not restore: {message}',
    'restoreReplaceWarning':
        'Restore will replace all current data on this device.',
    'restoreSuccess': 'Data restored successfully.',
    'restoreFromJson': 'Restore from JSON file',
    'saveBudget': 'Save budget',
    'saveGoal': 'Save goal',
    'saveTransaction': 'Save transaction',
    'resetData': 'Reset data',
    'resetDataConfirmTitle': 'Confirm data reset',
    'resetDataSuccess': 'Data reset to the initial state.',
    'resetDataSubtitle': 'Requires confirmation before deletion',
    'resetDataWarning':
        'This will delete current financial data and recreate the initial sample data.',
    'searchTransactions': 'Search by note or category',
    'settings': 'Settings',
    'sharePdf': 'Share PDF',
    'systemTheme': 'System',
    'theme': 'Theme',
    'thisMonthIncome': 'This month income',
    'type': 'Type',
    'thisMonthExpense': 'This month expense',
    'topExpenseCategories': 'Top spending categories',
    'topExpenseCategoriesEmpty': 'Not enough ranking data yet',
    'totalBalance': 'Current total balance',
    'transactions': 'Transactions',
    'transactionSearchEmpty': 'No matching transactions',
    'transfer': 'Transfer',
    'transactionSaveFailed': 'Could not save transaction on this device',
    'transferBetweenWallets': 'Transfer between wallets',
    'transferNow': 'Transfer now',
    'transferring': 'Transferring...',
    'value': 'Value',
    'updateBudget': 'Update budget',
    'updateGoal': 'Update goal',
    'unknownError': 'Could not complete the action on this device',
    'updateTransaction': 'Update transaction',
    'pinCreateSubtitle':
        'Create a 4-6 digit PIN to lock financial data on this device.',
    'password': 'Password',
    'premiumActive': 'Premium is active',
    'premiumLocked': 'Free account, premium features locked',
    'register': 'Register',
    'syncAuthFailed': 'Could not sign in. Check email, password, or network.',
    'syncNow': 'Sync',
    'syncServerUnavailable': 'Sync server unavailable',
    'syncSessionUnavailable': 'Could not read sync session on this device',
    'syncStatusSynced': 'Account status synced',
    'themeDark': 'Dark',
    'themeLight': 'Light',
    'walletCash': 'Cash',
    'walletBank': 'Bank',
    'walletCreditCard': 'Credit card',
    'walletDestination': 'Destination wallet',
    'walletEWallet': 'E-wallet',
    'walletSameTransferError':
        'Source and destination wallets must be different',
    'walletSource': 'Source wallet',
    'wallets': 'Wallets',
  },
  'ja': {
    'addBudget': '予算を追加',
    'addGoal': '目標を追加',
    'addTransaction': '取引を追加',
    'all': 'すべて',
    'allCategories': 'すべてのカテゴリ',
    'allMonths': 'すべての月',
    'allWallets': 'すべてのウォレット',
    'amount': '金額',
    'accountSync': 'アカウントと同期',
    'accountSyncSignedOut': 'ログインするとクラウド同期、Premium、共有予算を利用できます。',
    'amountInvalid': '金額が正しくありません',
    'amountPositive': '金額は0より大きくしてください',
    'backupCreated': 'バックアップJSONファイルを作成しました。',
    'backupExportFailed': 'この端末でバックアップを出力できませんでした。',
    'backupIntro': 'オフラインJSONファイルを出力、またはCashFlow Managerバックアップから復元します。',
    'backupRestore': 'バックアップ / 復元',
    'backupRestoreData': 'データのバックアップ / 復元',
    'backupRestoreSubtitle': 'オフラインJSONファイルを出力・復元',
    'backupSensitiveWarning':
        'バックアップファイルには機密性の高い金融データが含まれます。信頼できる場所でのみ共有または保存してください。',
    'backupCategoryRequired': 'バックアップには少なくとも1つのカテゴリが必要です',
    'backupDuplicateId': 'バックアップに重複したデータIDがあります',
    'backupInvalidDate': 'バックアップの日付が正しくありません',
    'backupInvalidExportTime': '出力時間が正しくありません',
    'backupInvalidFile': 'バックアップファイルが正しくありません',
    'backupInvalidRow': 'バックアップのデータ行が正しくありません',
    'backupInvalidType': 'バックアップのデータ種別が正しくありません',
    'backupMissingCategoryReference': 'バックアップが存在しないカテゴリを参照しています',
    'backupMissingData': 'バックアップに必須データがありません',
    'backupMissingField': 'バックアップに必須フィールドがありません',
    'backupMissingTargetWalletReference': 'バックアップが存在しない送金先ウォレットを参照しています',
    'backupMissingWalletReference': 'バックアップが存在しないウォレットを参照しています',
    'backupNonNegativeNumberRequired': 'バックアップに不正な負の金額があります',
    'backupPositiveNumberRequired': 'バックアップに0より大きい必要がある金額があります',
    'backupUnsupportedVersion': '対応していないバックアップバージョンです',
    'backupWalletRequired': 'バックアップには少なくとも1つのウォレットが必要です',
    'biometricFailed': '生体認証に失敗しました',
    'biometricUnlock': '生体認証で解除',
    'biometricUnlockSetting': '生体認証で解除',
    'biometricUnlockEnabled': '次回の解除で有効',
    'biometricUnlockDisabled': '認証して有効化するまでオフ',
    'biometricEnableReason': '生体認証での解除を有効にするため認証してください',
    'biometricEnableFailed': '生体認証を有効にできませんでした。PINは引き続き使えます。',
    'biometricRequiresPin': '生体認証を有効にする前にPINを作成してください',
    'biometricUnavailable': 'この端末では生体認証を利用できません',
    'budgetAlerts': '予算アラート',
    'budgetThisMonth': '今月の予算',
    'budgets': '予算',
    'cancel': 'キャンセル',
    'cashflowForecast': 'キャッシュフロー予測',
    'cashflowThisMonth': '今月の収入と支出',
    'category': 'カテゴリ',
    'categoryExpense': '支出カテゴリ',
    'categoryExpenseChartEmpty': '今月の支出はまだありません',
    'close': '閉じる',
    'currency': '既定の通貨',
    'csvTransactions': 'CSV取引',
    'dashboard': '概要',
    'defaultCurrency': 'VND',
    'delete': '削除',
    'deleteBudget': '予算を削除',
    'deleteBudgetQuestion': '予算を削除しますか？',
    'deleteBudgetWarning': 'この予算は選択した月から削除されます。',
    'deleteGoal': '目標を削除',
    'deleteGoalQuestion': '目標を削除しますか？',
    'deleteGoalWarning': 'この貯蓄目標は削除されます。',
    'deleteTransaction': '取引を削除',
    'deleteTransactionQuestion': '取引を削除しますか？',
    'date': '日付',
    'email': 'メール',
    'expense': '支出',
    'expenseCategoryChart': 'カテゴリ別支出',
    'expenseWalletCategory': 'ウォレット / 口座',
    'exportBackupJson': 'バックアップJSONを出力',
    'exportCsvPdf': 'CSV/PDFを出力',
    'exportReportContent': 'レポート出力内容',
    'exportSensitiveWarning':
        '出力されたレポートには機密性の高い金融データが含まれる場合があります。信頼できる相手やアプリとのみ共有してください。',
    'forecastCurrentMonthEnd': '今月末の予測',
    'forecastNextMonthEnd': '翌月末の予測',
    'futureCashflow': '将来のキャッシュフロー',
    'goalName': '目標名',
    'goalSavedAmount': '貯蓄済み金額',
    'goalSavedExceedsTarget': '貯蓄済み金額が目標金額を超えています',
    'goalTargetAmount': '目標金額',
    'goals': '貯蓄目標',
    'income': '収入',
    'language': '言語',
    'languageEnglish': '英語',
    'languageJapanese': '日本語',
    'languageVietnamese': 'ベトナム語',
    'login': 'ログイン',
    'logout': 'ログアウト',
    'loadDataFailed': 'データを読み込めませんでした',
    'monthlyLimit': '月間上限',
    'monthAfter': '翌月',
    'monthBefore': '前月',
    'metric': '指標',
    'monthlyReportTextTitle': 'CashFlow Manager - 月次レポート',
    'monthFilter': '月で絞り込み',
    'netCashflow': '純キャッシュフロー',
    'nextBills': '今後の請求リマインダー',
    'monthlyTrend': '4か月の収支トレンド',
    'includedInForecast': '予測に反映済み',
    'noTrendData': 'トレンドデータはまだありません',
    'noBudgets': '予算はまだありません',
    'noRecurringExpenses': '定期的な支出はまだありません',
    'noSavingGoals': '貯蓄目標はまだありません',
    'noTransactions': '取引はまだありません',
    'note': 'メモ',
    'recentTransactions': '最近の取引',
    'confirm': '確認',
    'reauthSubtitle': '金融データを変更または置き換える前に、もう一度PINを入力してください。',
    'reauthTitle': '再認証',
    'reportMonth': '月次レポート',
    'reports': 'レポート',
    'recurringTransaction': '定期取引',
    'pinConfirm': 'PINを再入力',
    'pinCooldownActive': 'PINの入力を何度も間違えました。5分後にもう一度お試しください。',
    'pinCreate': 'PINを作成',
    'pinCreateTitle': '金融データを保護',
    'pinInvalid': 'PINが正しくありません',
    'pinMismatch': '確認用PINが一致しません',
    'pinLengthInvalid': 'PINは4〜6桁にしてください',
    'pinNew': '新しいPIN',
    'pinSaveFailed': 'この端末でPINを保存できませんでした',
    'pinUnlock': '解除',
    'pinUnlockFailed': 'この端末でPINを確認できませんでした',
    'pinUnlockSubtitle': '支出管理を続けるにはPINを入力してください。',
    'pinUnlockTitle': 'CashFlow Managerを解除',
    'privacyLock': 'プライバシーロック / PIN',
    'privacyLockEnabled': '有効',
    'privacyLockDisabled': '未設定',
    'privacyLockSubtitle': 'PINは常に利用でき、生体認証は任意で有効化します。',
    'restoreCancelled': 'データ復元をキャンセルしました。',
    'restoreConfirm': '復元',
    'restoreConfirmTitle': 'データ復元の確認',
    'restoreExportMissing': '出力時間なし',
    'restoreFailed': 'この端末でバックアップを復元できませんでした。',
    'restoreFileReadFailed': 'バックアップファイルを読み取れません',
    'restoreFileTooLarge': 'バックアップファイルが5MBを超えています',
    'restoreFormatFailed': '復元できません: {message}',
    'restoreReplaceWarning': '復元すると、この端末の現在のデータはすべて置き換えられます。',
    'restoreSuccess': 'データを復元しました。',
    'restoreFromJson': 'JSONファイルから復元',
    'saveBudget': '予算を保存',
    'saveGoal': '目標を保存',
    'saveTransaction': '取引を保存',
    'resetData': 'データをリセット',
    'resetDataConfirmTitle': 'データリセットの確認',
    'resetDataSuccess': 'データを初期状態にリセットしました。',
    'resetDataSubtitle': '削除前に確認が必要です',
    'resetDataWarning': '現在の金融データを削除し、初期サンプルデータを再作成します。',
    'searchTransactions': 'メモまたはカテゴリで検索',
    'settings': '設定',
    'sharePdf': 'PDFを共有',
    'systemTheme': 'システム',
    'theme': 'テーマ',
    'thisMonthIncome': '今月の収入',
    'type': '種類',
    'thisMonthExpense': '今月の支出',
    'topExpenseCategories': '支出が多いカテゴリ',
    'topExpenseCategoriesEmpty': 'ランキングに十分なデータがまだありません',
    'totalBalance': '現在の合計残高',
    'transactions': '取引',
    'transactionSearchEmpty': '一致する取引はありません',
    'transfer': '送金',
    'transactionSaveFailed': 'この端末で取引を保存できませんでした',
    'transferBetweenWallets': 'ウォレット間で送金',
    'transferNow': '送金する',
    'transferring': '送金中...',
    'value': '値',
    'updateBudget': '予算を更新',
    'updateGoal': '目標を更新',
    'unknownError': 'この端末で操作を完了できませんでした',
    'updateTransaction': '取引を更新',
    'pinCreateSubtitle': 'この端末の金融データをロックする4〜6桁のPINを作成してください。',
    'password': 'パスワード',
    'premiumActive': 'Premium が有効です',
    'premiumLocked': '無料アカウントです。Premium 機能はロック中です',
    'register': '登録',
    'syncAuthFailed': 'ログインできません。メール、パスワード、またはネットワークを確認してください。',
    'syncNow': '同期',
    'syncServerUnavailable': '同期サーバーを利用できません',
    'syncSessionUnavailable': 'この端末の同期セッションを読み取れません',
    'syncStatusSynced': 'アカウント状態を同期しました',
    'themeDark': 'ダーク',
    'themeLight': 'ライト',
    'walletCash': '現金',
    'walletBank': '銀行',
    'walletCreditCard': 'クレジットカード',
    'walletDestination': '送金先ウォレット',
    'walletEWallet': '電子ウォレット',
    'walletSameTransferError': '送金元と送金先のウォレットは別にしてください',
    'walletSource': '送金元ウォレット',
    'wallets': 'ウォレット',
  },
};
